apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hqngxm29v-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/hqngxm29v-java-quarkus-gitops